# @package _global_

defaults:
  - override /data: r1lite/arm #_torso_velocity_chassis
  - override /model: vla/g0plus

model:
  pretrained_ckpt: /root/ckpts/G0Plus_3B_base/checkpoints/model_state_dict.pt
  batch_size: 8
  num_workers: 4
  grad_accumulation_steps: 1
  max_steps: 30000
  max_epochs: null
  # LoRA configuration (uncomment to enable LoRA fine-tuning)
  use_lora: True
  find_unused_parameters: True
  lora:
    r: 16
    alpha: 32
    dropout: 0.1
    bias: "none"
    target_modules: ["q_proj", "v_proj", "k_proj", "o_proj"]
    apply_to_vlm: True
    apply_to_action: True
  model_arch:
    joint:
      gradient_checkpointing: True  # Enable to save memory at cost of extra compute
    pretrained_model_path: /root/ckpts/paligemma-3b-pt-224
    action_dim: 14
    proprio_dim: 14
  processor:
    tokenizer_params: 
      pretrained_model_name_or_path: /root/ckpts/paligemma-3b-pt-224
    action_state_transforms: 
      - _target_: galaxea_fm.transforms.relative_action.RelativeJointTransform
        keys: [left_arm, right_arm]

data:
  val_set_proportion: 0.00
  dataset_dirs: 
    - /root/data_convert/data/lerobot/20260119_hdf5
    # - /data/galaxa_openworld/Arrange_Mineral_Water_Bottles_On_The_Desk_20250721_008
    # - /data/galaxa_openworld/Organize_Mineral_Water_Bottles_0n_The_Table_20250709_006 
    # - /root/data/G0Plus_Finetune_LeRobot_Datasets_Demo/BENCH_Pick_And_Place_20_Items16_Evenly_Distributed_Round_13_20251022_018
    # - /root/data/G0Plus_Finetune_LeRobot_Datasets_Demo/BENCH_Pick_And_Place_20_Items57_Evenly_Distributed_Round_13_20251024_018

logger:
  workspace: Oshwiciqwq

batch_size_val: 1
eval_steps: 1000

checkpointing_steps: 5000